import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NotificationProvider } from "@/context/NotificationContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps{
  children: React.ReactNode
}

export default function RootLayout ({ children }: RootLayoutProps){
  return (
    <html lang="en">
      <body className={inter.className}>
        <NotificationProvider>
          <main className="min-h-screen flex flex-col items-center justify-center">
            {children}
          </main>
        </NotificationProvider>
      </body>
    </html>
  )
}
